# ==============================================================
#  periodic_plane_wave.jl — plane wave in a PERIODIC-width flume
#
#  Long-crested plane wave propagating in x, generated by a Gaussian LINE
#  source (y-invariant), in a flume whose lateral (y) boundaries are PERIODIC
#  (y_wall_bc=:periodic). The top and bottom edges are identified, so the domain
#  is the numerical realisation of an infinite-width flume: no lateral walls, no
#  lateral sponges — the line source is y-invariant hence perfectly compatible
#  with the periodicity, and the plane wave stays clean across the seam.
#
#  This is the demonstrator for the :periodic lateral boundary condition. The
#  x-ends keep sponge layers (open flume); only the y-edges are periodic.
#
#  RUN:  julia --project=. GridapLFEM.jl/examples/periodic_plane_wave.jl
# ==============================================================

if !isdefined(Main, :GridapLFEM)
    include(joinpath(@__DIR__, "..", "src", "GridapLFEM.jl"))
end
using .GridapLFEM
using Printf

println("=" ^ 60)
println("  periodic_plane_wave.jl — plane wave, PERIODIC y-boundaries")
println("=" ^ 60)

# ── Physical parameters (linear regime, kd = 5.5) ─────────────
h_val  = 3.5
T_wave = 1.6
A_wave = 0.001
g      = 9.81

# ── Domain (narrow, periodic-width strip; a plane wave is y-invariant) ─
Lx, Ly = 100.0, 8.0
nx, ny = 200, 8

# ── Time stepping (quick default) ─────────────────────────────
T_final = 8.0 * T_wave
dt      = T_wave / 30

# ── Sponge (x-ends only) and wavemaker ────────────────────────
x_wm      = 15.0
sponge_wL = 15.0
sponge_wR = 20.0
mu_max    = 5.0

# ── Wave gauges (probe at three y-levels to check y-invariance) ─
gauges = [(x_wm + 8*4.0, 0.5),          # near the bottom periodic edge
          (x_wm + 8*4.0, Ly/2),         # centre
          (x_wm + 8*4.0, Ly - 0.5)]     # near the top periodic edge

diags, vert, prob = setup_and_run(
    M           = 2,
    flat_bed    = true,   # flat sea bed (∇h≡0)
    c_bdy       = [0.0, 0.728, 1.0],
    domain      = ((0.0, Lx), (0.0, Ly)),
    partition   = (nx, ny),
    p_horizontal    = 2,
    h_val       = h_val,
    g           = g,
    T_wave      = T_wave,
    A_wave      = A_wave,
    wave_gen    = :inner_res,       # interior Gaussian source
    x_wm        = x_wm,
    y_wm        = nothing,          # line source → plane wave (y-invariant)
    sponge_wL   = sponge_wL,
    sponge_wR   = sponge_wR,
    sponge_wB   = 0.0,              # NO lateral sponges — the y-edges are periodic
    sponge_wT   = 0.0,
    mu_max      = mu_max,
    T_final     = T_final,
    dt          = dt,
    y_wall_bc   = :periodic,        # ★ periodic lateral (y) boundaries
    x_wall_bc   = false,            # open x-ends (sponge-absorbed)
    linearised  = true,             # linear regime benchmark (A = 0.001)
    advection   = false,
    save_every  = 30,               # one VTK snapshot per period
    output_dir  = joinpath(@__DIR__, "..", "output", "periodic_plane_wave"),
    gauges      = gauges,
)

# ── Post ──────────────────────────────────────────────────────
emax = maximum(d.eta_max for d in diags)
@printf("\n  max η over run = %.5f m  (A = %.4f m)\n", emax, A_wave)
amps = Float64[]
for (i, gxy) in enumerate(gauges)
    gv = [d.gauge_vals[i] for d in diags if !isempty(d.gauge_vals)]
    n2 = length(gv) ÷ 2
    amp = isempty(gv) ? 0.0 : maximum(abs.(gv[n2:end]))
    push!(amps, amp)
    @printf("  gauge %d at (x=%.1f, y=%.2f):  steady amplitude ≈ %.5f m\n",
            i, gxy[1], gxy[2], amp)
end
# y-invariance check: the three gauges at different y should agree (periodic,
# y-invariant plane wave) — a large spread would signal a seam artefact.
spread = isempty(amps) ? 0.0 : (maximum(amps) - minimum(amps)) / max(maximum(amps), 1e-30)
@printf("  y-invariance (amplitude spread across y): %.2f%%\n", 100*spread)
println("\n  VTK output: GridapLFEM.jl/output/periodic_plane_wave/solution.pvd")
