# ==============================================================
#  run_irregular_sea_small.jl — PARAMETRIC small-domain irregular sea (BC gen)
#
#  ONE script for every long-crested (normal-incidence) JONSWAP sea generated by
#  time-varying Dirichlet data (eta, Ux) on the LEFT boundary, on the 50x20 m
#  small domain. Normal incidence => Uy == 0 => y_wall_bc=:wall. Covers cases
#  6, 15, 16. Physics/sea via environment variables.
#
#  Config via env (base = nonlinear / full pressure / flat bed / Hs=0.2):
#    LFEM_REGIME       linear | nonlinear                    (default nonlinear)
#    LFEM_NL_PRESSURE  none | native | full                  (default full)
#    LFEM_FLAT_BED     1 flat | 0 variable (=> submerged bar built here)   (1)
#    LFEM_HS / LFEM_TP     sea state Hs [m], Tp [s]          (default 0.2 / 2.0)
#    LFEM_HBAR/XBAR/WBAR   bar shape, used only when FLAT_BED=0   1.5 / 26 / 6
#
#  Fixed defaults: mesh 200x40, partition 8x4 (32 ranks), fe_order 2, dt 0.02,
#  d 3.5, right sponge 12, mu_max 8, inflow relaxation zone 6, periods 15,
#  save_every 10.
#
#  NOTE: uses build_airy_state => depends on the WaveSpec change_seed! fix.
#  LAUNCH (px*py MUST equal -n): see run/dist_small/*irregular*.sh
# ==============================================================

include(joinpath(@__DIR__, "..", "distributed", "_dist_common.jl"))

get!(ENV, "LFEM_REGIME", "nonlinear"); get!(ENV, "LFEM_NL_PRESSURE", "full")
get!(ENV, "LFEM_FLAT_BED", "1")
get!(ENV, "LFEM_HS", "0.2"); get!(ENV, "LFEM_TP", "2.0")
get!(ENV, "LFEM_NFREQ", "15")
get!(ENV, "LFEM_RELAX", "1"); get!(ENV, "LFEM_RELAX_W", "6")

M       = genv_i("LFEM_M", 2)
px, py  = genv_i("LFEM_PX", 8), genv_i("LFEM_PY", 4)      # 8*4 = 32 ranks
nx, ny  = genv_i("LFEM_NX", 200), genv_i("LFEM_NY", 40)
feord   = genv_i("LFEM_FE_ORDER", 2)
Lx, Ly  = genv_f("LFEM_LX", 50.0), genv_f("LFEM_LY", 20.0)
d       = genv_f("LFEM_D", 3.5)
spR     = genv_f("LFEM_SPONGE_R", 12.0)
mumax   = genv_f("LFEM_MUMAX", 40.0)   # strong: kill the outgoing/boundary mode fast
dt      = genv_f("LFEM_DT", 0.02)
periods = genv_f("LFEM_PERIODS", 15.0)
Tp      = tp_val()
Tfinal  = haskey(ENV, "LFEM_TFINAL") ? genv_f("LFEM_TFINAL", 0.0) : periods * Tp
save_ev = genv_i("LFEM_SAVE_EVERY", 10)

usebar  = !flat_bed_flag(1)
hbar    = genv_f("LFEM_HBAR", 1.5); xbar = genv_f("LFEM_XBAR", 26.0); wbar = genv_f("LFEM_WBAR", 6.0)
sramp   = wbar / 3.0
h_bathy = usebar ?
    (x -> d - 0.5*hbar*(tanh((x[1]-(xbar-wbar))/sramp) - tanh((x[1]-(xbar+wbar))/sramp))) : nothing

state   = build_airy_state(d; directional=false)
bedtag  = usebar ? "bar" : "flat"
tag     = "$(regime_sym())_$(nl_pressure_sym())_$(bedtag)_Hs$(hs_val())"
outdir  = genv("LFEM_OUTDIR", joinpath(ROOT, "output", "small_irregular_$(tag)_M$(M)"))

banner("SMALL | irregular sea (Dirichlet BC) | $(regime_sym()) $(nl_pressure_sym()) $bedtag Hs=$(hs_val())",
       M, (px,py), (nx,ny), nx*ny, outdir)
is_rank0() && @printf("#   Hs=%.4g m Tp=%.3g s | bed=%s bc_side=%s profile=%s seed=%d\n",
                      hs_val(), Tp, bedtag, string(bc_side_sym()),
                      string(bc_profile_sym()), genv_i("LFEM_SEED", 20260723))

diags, vert, prob = setup_and_run_distributed(
    cpu_grid=(px,py), M=M, c_bdy=cbdy_override(), p_horizontal=feord,
    domain=(0.0,Lx,0.0,Ly), partition=(nx,ny),
    h_val=d, T_wave=Tp, A_wave=hs_val()/2,
    wave_gen=:bc_gen, wave_bc=state, bc_side=bc_side_sym(), bc_profile=bc_profile_sym(),
    T_ramp=tramp_val(), relax_bc=relax_flag(), relax_width=relax_w_val(),
    sponge_wL=0.0, sponge_wR=spR, sponge_wB=0.0, sponge_wT=0.0, mu_max=mumax,
    T_final=Tfinal, dt=dt, h_bathy=h_bathy,
    regime=regime_sym(), nl_pressure=nl_pressure_sym(), flat_bed=flat_bed_flag(1),
    y_wall_bc=:wall, x_wall_bc=false,                              # long-crested => Uy == 0
    output_dir=outdir, save_every=save_ev,
    write_w=genv_b("LFEM_WRITE_W", 0), write_pressure=genv_b("LFEM_WRITE_PRESSURE", 0),
    rho=rho_val(),
    solver_type=solver_sym(), tableau=tableau_sym(),
    nl_iter=nl_iter_val(), nl_tol=nl_tol_val(),
    ls_rtol=ls_rtol_val(), ls_maxiter=ls_maxiter_val(),
    print_every=genv_i("LFEM_PRINT_EVERY", 10))

is_rank0() && @printf("irregular_sea [%s] done: %d steps, %d snapshots to %s\n",
                      tag, length(diags), save_ev > 0 ? length(diags) ÷ save_ev : 0, outdir)
