# ==============================================================
#  run_directional_sea_small.jl — PARAMETRIC small-domain directional sea (BC gen)
#
#  ONE script for every short-crested (directional) JONSWAP sea generated by
#  time-varying Dirichlet data (eta, Ux, Uy) on the LEFT boundary, on the 50x20 m
#  small domain. Directional seas prescribe Uy != 0 => y_wall_bc=:open (lateral
#  sponges). Covers cases 5, 13, 14. Physics/sea via environment variables.
#
#  Config via env (base = nonlinear / full pressure / flat bed / Hs=0.2):
#    BALFEM_REGIME       linear | nonlinear                    (default nonlinear)
#    BALFEM_NL_PRESSURE  none | native | full                  (default full)
#    BALFEM_FLAT_BED     1 flat | 0 variable (=> shore-parallel bar built here) (1)
#    BALFEM_HS / BALFEM_TP     sea state Hs [m], Tp [s]          (default 0.2 / 2.0)
#    BALFEM_NTHETA / BALFEM_SPREAD_STD / BALFEM_THETA_MAX  spreading  (7 / 15deg / 40deg)
#    BALFEM_HBAR/XBAR/WBAR   bar shape, used only when FLAT_BED=0   1.5 / 26 / 6
#
#  Fixed defaults: mesh 200x80 (square cells), partition 8x8 (64 ranks), p_horizontal
#  2, dt 0.02, d 3.5, right sponge 12, lateral sponges 8, mu_max 40, inflow
#  relaxation zone ON (width 6 m), periods 26 (transit-based), save_every 10.
#
#  DURATION: same transit argument as the irregular sea (generation x=0, sponge
#  from x=38, 22 Tp needed at Tp=1.6). Obliquely-incident components travel a
#  LONGER path to the outflow, so 26 Tp is the floor here, not a generous margin.
#
#  NOTE: uses build_airy_state => depends on the WaveSpec change_seed! fix.
#  LAUNCH (px*py MUST equal -n): see run/dist_small/*directional*.sh
# ==============================================================

include(joinpath(@__DIR__, "..", "distributed", "_dist_common.jl"))

get!(ENV, "BALFEM_REGIME", "nonlinear"); get!(ENV, "BALFEM_NL_PRESSURE", "full")
get!(ENV, "BALFEM_FLAT_BED", "1")
get!(ENV, "BALFEM_HS", "0.2"); get!(ENV, "BALFEM_TP", "2.0")
get!(ENV, "BALFEM_NFREQ", "15"); get!(ENV, "BALFEM_NTHETA", "7")
get!(ENV, "BALFEM_SPREAD_STD", "15"); get!(ENV, "BALFEM_THETA_MAX", "40")
get!(ENV, "BALFEM_RELAX", "1"); get!(ENV, "BALFEM_RELAX_W", "6")

M       = genv_i("BALFEM_M", 2)

#  Vertical BASIS ORDER. The model is named P{p_vert}LFE-{M}: `Pp` is the

#  vertical Lagrange order and `M` the number of vertical elements, so the run

#  says which member of the BALFE-M family it actually exercises. Default p=1

#  reproduces the piecewise-linear models of Yang & Liu.

p_vert  = genv_i("BALFEM_P_VERT", 1)

model_name = "P$(p_vert)LFE-$(M)"
px, py  = genv_i("BALFEM_PX", 8), genv_i("BALFEM_PY", 8)      # 8*8 = 64 ranks
nx, ny  = genv_i("BALFEM_NX", 200), genv_i("BALFEM_NY", 80)   # square cells 0.25x0.25
feord   = genv_i("BALFEM_FE_ORDER", 2)
#  p_eta = 0 keeps the historical EQUAL-ORDER spaces (unchanged default).
#  Set BALFEM_P_ETA = BALFEM_FE_ORDER-1 for the Taylor-Hood-like pairing, which is
#  the only one measured to reach the theoretical order in BOTH fields. It is
#  NOT automatically the better production choice: at a GIVEN mesh the
#  equal-order spaces were 40x more accurate, because eta sits in a richer
#  space. Compare error-vs-DOF before switching.
p_eta   = genv_i("BALFEM_P_ETA", 0)
Lx, Ly  = genv_f("BALFEM_LX", 50.0), genv_f("BALFEM_LY", 20.0)
d       = genv_f("BALFEM_D", 3.5)
spR     = genv_f("BALFEM_SPONGE_R", 12.0)
#  LATERAL sponges take the obliquely-propagating components, so they must be
#  sized against the sea, not against Tp. The energy-carrying band reaches
#  T ~ 1.5*Tp (longer components carry <0.12 % of the variance), i.e.
#  lambda_eff = 8.9 m. 4.0 m was 0.45 lambda_eff; 8 m is 0.90 — still slightly
#  under one wavelength, which is the most a 20 m wide domain can give. Widen
#  BALFEM_LY together with this if lateral reflection shows up in the diagnostics.
spY     = genv_f("BALFEM_SPONGE_Y", 8.0)
mumax   = genv_f("BALFEM_MUMAX", 40.0)   # strong: kill the outgoing/boundary mode fast
dt      = genv_f("BALFEM_DT", 0.02)
periods = genv_f("BALFEM_PERIODS", 26.0)   # 19 Tp transit + 3 Tp; oblique paths are longer
Tp      = tp_val()
Tfinal  = haskey(ENV, "BALFEM_TFINAL") ? genv_f("BALFEM_TFINAL", 0.0) : periods * Tp
save_ev = genv_i("BALFEM_SAVE_EVERY", 10)

# bathymetry: flat_bed=false => variable bathymetry => shore-parallel submerged bar
usebar  = !flat_bed_flag(1)
hbar    = genv_f("BALFEM_HBAR", 1.5); xbar = genv_f("BALFEM_XBAR", 26.0); wbar = genv_f("BALFEM_WBAR", 6.0)
sramp   = wbar / 3.0
h_bathy = usebar ?
    (x -> d - 0.5*hbar*(tanh((x[1]-(xbar-wbar))/sramp) - tanh((x[1]-(xbar+wbar))/sramp))) : nothing

state   = build_airy_state(d; directional=true)
bedtag  = usebar ? "bar" : "flat"
tag     = "$(regime_sym())_$(nl_pressure_sym())_$(bedtag)_Hs$(hs_val())"
outdir  = genv("BALFEM_OUTDIR", joinpath(ROOT, "output", "small_directional_$(tag)_$(model_name)"))

banner("SMALL | directional sea (Dirichlet BC) | $(regime_sym()) $(nl_pressure_sym()) $bedtag Hs=$(hs_val())",
       M, (px,py), (nx,ny), nx*ny, outdir)
is_rank0() && @printf("#   Hs=%.4g m Tp=%.3g s | nth=%d sth=%.1f thmax=%.1f | bed=%s seed=%d\n",
                      hs_val(), Tp, genv_i("BALFEM_NTHETA", 7), genv_f("BALFEM_SPREAD_STD", 15.0),
                      genv_f("BALFEM_THETA_MAX", 40.0), bedtag, genv_i("BALFEM_SEED", 20260723))

diags, vert, prob = setup_and_run_distributed(
    cpu_grid=(px,py), M=M, p_vertical=p_vert, c_bdy=cbdy_override(), p_horizontal=feord, p_eta=p_eta,
    domain=(0.0,Lx,0.0,Ly), partition=(nx,ny),
    h_val=d, T_wave=Tp, A_wave=hs_val()/2,
    wave_gen=:bc_gen, wave_bc=state, bc_side=bc_side_sym(), bc_profile=bc_profile_sym(),
    #  relax_bc defaults ON here: sponge_wL=0, so without the relaxation zone NOTHING
    #  absorbs what the domain radiates back at the clamped Dirichlet inflow.
    T_ramp=tramp_val(), relax_bc=genv_b("BALFEM_RELAX", 1),
    relax_width=genv_f("BALFEM_RELAX_W", 6.0),
    sponge_wL=0.0, sponge_wR=spR, sponge_wB=spY, sponge_wT=spY, mu_max=mumax,
    T_final=Tfinal, dt=dt, h_bathy=h_bathy,
    regime=regime_sym(), nl_pressure=nl_pressure_sym(), flat_bed=flat_bed_flag(1),
    y_wall_bc=:open, x_wall_bc=false,                              # Uy != 0 at the inflow
    output_dir=outdir, save_every=save_ev,
    write_w=genv_b("BALFEM_WRITE_W", 0), write_pressure=genv_b("BALFEM_WRITE_PRESSURE", 0),
    rho=rho_val(),
    solver_type=solver_sym(), tableau=tableau_sym(),
    nl_iter=nl_iter_val(), nl_tol=nl_tol_val(),
    ls_rtol=ls_rtol_val(), ls_maxiter=ls_maxiter_val(), krylov_m=krylov_m_val(), precond=precond_sym(),
    diag_every=diag_every_val(), diag_csv=diag_csv_flag(),
    div_factor=div_factor_val(), eta_ref=eta_ref_val(),
    print_every=genv_i("BALFEM_PRINT_EVERY", 10))

is_rank0() && @printf("directional_sea [%s] done: %d steps, %d snapshots to %s\n",
                      tag, length(diags), save_ev > 0 ? length(diags) ÷ save_ev : 0, outdir)
