# ==============================================================
#  run_directional_sea_small.jl — PARAMETRIC small-domain directional sea (BC gen)
#
#  ONE script for every short-crested (directional) JONSWAP sea generated by
#  time-varying Dirichlet data (eta, Ux, Uy) on the LEFT boundary, on the 50x20 m
#  small domain. Directional seas prescribe Uy != 0 => y_wall_bc=:open (lateral
#  sponges). Covers cases 5, 13, 14. Physics/sea via environment variables.
#
#  Config via env (base = nonlinear / full pressure / flat bed / Hs=0.2):
#    LFEM_REGIME       linear | nonlinear                    (default nonlinear)
#    LFEM_NL_PRESSURE  none | native | full                  (default full)
#    LFEM_FLAT_BED     1 flat | 0 variable (=> shore-parallel bar built here) (1)
#    LFEM_HS / LFEM_TP     sea state Hs [m], Tp [s]          (default 0.2 / 2.0)
#    LFEM_NTHETA / LFEM_SPREAD_STD / LFEM_THETA_MAX  spreading  (7 / 15deg / 40deg)
#    LFEM_HBAR/XBAR/WBAR   bar shape, used only when FLAT_BED=0   1.5 / 26 / 6
#
#  Fixed defaults: mesh 200x80 (square cells), partition 8x8 (64 ranks), fe_order
#  2, dt 0.02, d 3.5, right sponge 12, lateral sponges 4, mu_max 8, inflow
#  relaxation zone 6, periods 15, save_every 10.
#
#  NOTE: uses build_airy_state => depends on the WaveSpec change_seed! fix.
#  LAUNCH (px*py MUST equal -n): see run/dist_small/*directional*.sh
# ==============================================================

include(joinpath(@__DIR__, "..", "distributed", "_dist_common.jl"))

get!(ENV, "LFEM_REGIME", "nonlinear"); get!(ENV, "LFEM_NL_PRESSURE", "full")
get!(ENV, "LFEM_FLAT_BED", "1")
get!(ENV, "LFEM_HS", "0.2"); get!(ENV, "LFEM_TP", "2.0")
get!(ENV, "LFEM_NFREQ", "15"); get!(ENV, "LFEM_NTHETA", "7")
get!(ENV, "LFEM_SPREAD_STD", "15"); get!(ENV, "LFEM_THETA_MAX", "40")
get!(ENV, "LFEM_RELAX", "1"); get!(ENV, "LFEM_RELAX_W", "6")

M       = genv_i("LFEM_M", 2)
px, py  = genv_i("LFEM_PX", 8), genv_i("LFEM_PY", 8)      # 8*8 = 64 ranks
nx, ny  = genv_i("LFEM_NX", 200), genv_i("LFEM_NY", 80)   # square cells 0.25x0.25
feord   = genv_i("LFEM_FE_ORDER", 2)
Lx, Ly  = genv_f("LFEM_LX", 50.0), genv_f("LFEM_LY", 20.0)
d       = genv_f("LFEM_D", 3.5)
spR     = genv_f("LFEM_SPONGE_R", 12.0)
spY     = genv_f("LFEM_SPONGE_Y", 4.0)
mumax   = genv_f("LFEM_MUMAX", 8.0)
dt      = genv_f("LFEM_DT", 0.02)
periods = genv_f("LFEM_PERIODS", 15.0)
Tp      = tp_val()
Tfinal  = haskey(ENV, "LFEM_TFINAL") ? genv_f("LFEM_TFINAL", 0.0) : periods * Tp
save_ev = genv_i("LFEM_SAVE_EVERY", 10)

# bathymetry: flat_bed=false => variable bathymetry => shore-parallel submerged bar
usebar  = !flat_bed_flag(1)
hbar    = genv_f("LFEM_HBAR", 1.5); xbar = genv_f("LFEM_XBAR", 26.0); wbar = genv_f("LFEM_WBAR", 6.0)
sramp   = wbar / 3.0
h_bathy = usebar ?
    (x -> d - 0.5*hbar*(tanh((x[1]-(xbar-wbar))/sramp) - tanh((x[1]-(xbar+wbar))/sramp))) : nothing

state   = build_airy_state(d; directional=true)
bedtag  = usebar ? "bar" : "flat"
tag     = "$(regime_sym())_$(nl_pressure_sym())_$(bedtag)_Hs$(hs_val())"
outdir  = genv("LFEM_OUTDIR", joinpath(ROOT, "output", "small_directional_$(tag)_M$(M)"))

banner("SMALL | directional sea (Dirichlet BC) | $(regime_sym()) $(nl_pressure_sym()) $bedtag Hs=$(hs_val())",
       M, (px,py), (nx,ny), nx*ny, outdir)
is_rank0() && @printf("#   Hs=%.4g m Tp=%.3g s | nth=%d sth=%.1f thmax=%.1f | bed=%s seed=%d\n",
                      hs_val(), Tp, genv_i("LFEM_NTHETA", 7), genv_f("LFEM_SPREAD_STD", 15.0),
                      genv_f("LFEM_THETA_MAX", 40.0), bedtag, genv_i("LFEM_SEED", 20260723))

diags, vert, prob = setup_and_run_distributed(
    cpu_grid=(px,py), M=M, c_bdy=cbdy_override(), p_horizontal=feord,
    domain=(0.0,Lx,0.0,Ly), partition=(nx,ny),
    h_val=d, T_wave=Tp, A_wave=hs_val()/2,
    wave_bc=state, bc_side=bc_side_sym(), bc_profile=bc_profile_sym(),
    T_ramp=tramp_val(), relax_bc=relax_flag(), relax_width=relax_w_val(),
    sponge_wL=0.0, sponge_wR=spR, sponge_wB=spY, sponge_wT=spY, mu_max=mumax,
    T_final=Tfinal, dt=dt, h_bathy=h_bathy,
    regime=regime_sym(), nl_pressure=nl_pressure_sym(), flat_bed=flat_bed_flag(1),
    y_wall_bc=:open, x_wall_bc=false,                              # Uy != 0 at the inflow
    output_dir=outdir, save_every=save_ev,
    write_w=genv_b("LFEM_WRITE_W", 0), write_pressure=genv_b("LFEM_WRITE_PRESSURE", 0),
    rho=rho_val(),
    solver_type=solver_sym(), tableau=tableau_sym(),
    nl_iter=nl_iter_val(), nl_tol=nl_tol_val(),
    ls_rtol=ls_rtol_val(), ls_maxiter=ls_maxiter_val(),
    print_every=genv_i("LFEM_PRINT_EVERY", 10))

is_rank0() && @printf("directional_sea [%s] done: %d steps, %d snapshots to %s\n",
                      tag, length(diags), save_ev > 0 ? length(diags) ÷ save_ev : 0, outdir)
