# ==============================================================
#  run_lin_irregular_sea_small.jl — SMALL-DOMAIN sea-state comparison run
#
#  CASE 15/16:  LINEAR · irregular (long-crested) sea (BC gen) · flat bed · Hs=0.2
#  Long-crested (normal-incidence) JONSWAP sea generated by time-varying
#  Dirichlet data (η, 𝖴x) on the LEFT boundary, propagated with the LINEAR
#  dispersive model. Compared with case 6 (nonlinear-full, same Hs) the
#  difference is the finite-amplitude physics (bound harmonics, set-down); this
#  run is the clean linear reference. Normal incidence ⇒ 𝖴y ≡ 0, so y_wall_bc=:wall.
#
#  Geometry identical to case 6 (Dirichlet left, relaxation zone 6 m, right
#  sponge 12 m). Hs=0.2, Tp=2.0.
#
#  NOTE: uses build_airy_state ⇒ depends on the WaveSpec change_seed! fix.
#
#  LAUNCH (px·py MUST equal -n):
#    LFEM_PX=4 LFEM_PY=1 mpiexecjl --project=. -n 4 julia --project=. \
#        GridapLFEM.jl/examples/distributed_small/run_lin_irregular_sea_small.jl
#  (SLURM: run/dist_small/run_lin_irregular_sea_small.sh)
# ==============================================================

include(joinpath(@__DIR__, "..", "distributed", "_dist_common.jl"))

# ---- CASE 15 physics + long-crested sea defaults (env still overrides) ----
get!(ENV, "LFEM_REGIME", "linear"); get!(ENV, "LFEM_NL_PRESSURE", "none")
get!(ENV, "LFEM_FLAT_BED", "1")
get!(ENV, "LFEM_HS", "0.2"); get!(ENV, "LFEM_TP", "2.0")
get!(ENV, "LFEM_NFREQ", "15")
get!(ENV, "LFEM_RELAX", "1"); get!(ENV, "LFEM_RELAX_W", "6")

M        = genv_i("LFEM_M", 2)
px, py   = genv_i("LFEM_PX", 4), genv_i("LFEM_PY", 1)
nx, ny   = genv_i("LFEM_NX", 200), genv_i("LFEM_NY", 40)
feord    = genv_i("LFEM_FE_ORDER", 2)
Lx, Ly   = genv_f("LFEM_LX", 50.0), genv_f("LFEM_LY", 20.0)
d        = genv_f("LFEM_D", 3.5)
spR      = genv_f("LFEM_SPONGE_R", 12.0)
mumax    = genv_f("LFEM_MUMAX", 8.0)
dt       = genv_f("LFEM_DT", 0.02)
periods  = genv_f("LFEM_PERIODS", 15.0)
Tp       = tp_val()
Tfinal   = haskey(ENV, "LFEM_TFINAL") ? genv_f("LFEM_TFINAL", 0.0) : periods * Tp
save_ev  = genv_i("LFEM_SAVE_EVERY", 15)
outdir   = genv("LFEM_OUTDIR", joinpath(ROOT, "output", "small_lin_irregular_sea_M$(M)"))

state = build_airy_state(d; directional=false)

banner("SMALL | LINEAR IRREGULAR sea (Dirichlet BC, flat bed)",
       M, (px,py), (nx,ny), nx*ny, outdir)
is_rank0() && @printf("#   Hs=%.4g m Tp=%.3g s | bc_side=%s profile=%s seed=%d\n",
                      hs_val(), Tp, string(bc_side_sym()),
                      string(bc_profile_sym()), genv_i("LFEM_SEED", 20260723))

diags, vert, prob = setup_and_run_distributed(
    cpu_grid=(px,py), M=M, c_bdy=cbdy_override(), p_horizontal=feord,
    domain=(0.0,Lx,0.0,Ly), partition=(nx,ny),
    h_val=d, T_wave=Tp, A_wave=hs_val()/2,
    wave_bc=state, bc_side=bc_side_sym(), bc_profile=bc_profile_sym(),
    T_ramp=tramp_val(), relax_bc=relax_flag(), relax_width=relax_w_val(),
    sponge_wL=0.0, sponge_wR=spR, sponge_wB=0.0, sponge_wT=0.0, mu_max=mumax,
    T_final=Tfinal, dt=dt,
    regime=regime_sym(), nl_pressure=nl_pressure_sym(), flat_bed=flat_bed_flag(),  # ★ CASE 15 (defaults above)
    y_wall_bc=:wall, x_wall_bc=false,                              # long-crested ⇒ 𝖴y≡0, walls OK
    output_dir=outdir, save_every=save_ev,
    write_w=genv_b("LFEM_WRITE_W", 0), write_pressure=genv_b("LFEM_WRITE_PRESSURE", 0),
    rho=rho_val(),
    solver_type=solver_sym(), tableau=tableau_sym(),
    nl_iter=nl_iter_val(), nl_tol=nl_tol_val(),
    ls_rtol=ls_rtol_val(), ls_maxiter=ls_maxiter_val(),
    print_every=genv_i("LFEM_PRINT_EVERY", 10))

is_rank0() && @printf("small_lin_irregular_sea done: %d steps, %d snapshots to %s\n",
                      length(diags), save_ev > 0 ? length(diags) ÷ save_ev : 0, outdir)
